/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DA;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;

import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.util.Arrays;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class From_DoAn extends javax.swing.JFrame {

    boolean xacnhan = false;
    boolean hienTT = true;
    boolean hienMaTran = false;
    boolean hienLK = false;
    boolean duyet_Dothi_DFS = false;
    boolean duyet_Dothi_BFS = false;
    int select = 0;

    Thread[] thread1;
    paintOval[] pO_mang;
    Thread thread_2;
    paintOval pO;
    int t = 0;
    int temp_resize = 0;

    /**
     * Creates new form From_DoAn
     */
    public From_DoAn() {
        initComponents();
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("show.png"));
            Image ima = icon.getImage();
            setIconImage(ima);
        } catch (NullPointerException e) {
        }

        thread1 = new Thread[100];
        pO_mang = new paintOval[100];
        pO = new paintOval(pNShow2.getGraphics());
        this.setSize(1320, 920);
        sL_Resize.setValue(40);
        // mau btn
        btnAutoNoi.setBackground(Color.white);
        btnChay.setBackground(Color.white);
        btnHien_DT.setBackground(Color.white);
        btn_repair_vohuong.setBackground(Color.white);
        btn_TT_Dt.setBackground(Color.white);
        btn_Hien_lk.setBackground(Color.white);
        btnMaTran_DinhCanh.setBackground(Color.white);
        btnDanhSachKe.setBackground(Color.WHITE);
        btnDuyetDoTHi.setBackground(Color.white);
        this.rBDinh_Canh.setEnabled(false);
        this.rBCanh_max.setEnabled(false);

        //tieng viet
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        sL_Resize = new javax.swing.JSlider();
        lbSl_Show = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        char_Resize1 = new javax.swing.JSlider();
        lbchar_Show1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnHien_DT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_ShowResuilt = new javax.swing.JTextArea();
        btn_TT_Dt = new javax.swing.JButton();
        btn_Hien_lk = new javax.swing.JButton();
        pNShow2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnChay = new javax.swing.JButton();
        btnAutoNoi = new javax.swing.JButton();
        rBChi_Dinh = new javax.swing.JRadioButton();
        rBDinh_Canh = new javax.swing.JRadioButton();
        btn_repair_vohuong = new javax.swing.JButton();
        rBCanh_max = new javax.swing.JRadioButton();
        rBChi_Canh = new javax.swing.JRadioButton();
        rB_Khuyen = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnMaTran_DinhCanh = new javax.swing.JButton();
        btnDanhSachKe = new javax.swing.JButton();
        btnDuyetDoTHi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rB_Duyetdothi_BFS = new javax.swing.JRadioButton();
        rB_DuyetDoThi_DFS = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtA_temp = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lý Thuyết Đồ Thị");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());
        setIconImages(null);
        setResizable(false);
        setSize(new java.awt.Dimension(1205, 777));

        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 2, new java.awt.Color(51, 102, 255)));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Size nút:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        sL_Resize.setMaximum(80);
        sL_Resize.setMinimum(30);
        sL_Resize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sL_ResizeStateChanged(evt);
            }
        });

        lbSl_Show.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbSl_Show.setText("20");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sL_Resize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lbSl_Show)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(sL_Resize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(lbSl_Show)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Độ lớn chữ:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        char_Resize1.setMaximum(28);
        char_Resize1.setMinimum(10);
        char_Resize1.setValue(18);
        char_Resize1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                char_Resize1StateChanged(evt);
            }
        });

        lbchar_Show1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbchar_Show1.setText("20");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(char_Resize1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lbchar_Show1)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(char_Resize1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(lbchar_Show1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel11.getAccessibleContext().setAccessibleName("");

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 153, 255)));

        btnHien_DT.setText("Ma trận kề");
        btnHien_DT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHien_DTActionPerformed(evt);
            }
        });

        txtA_ShowResuilt.setColumns(20);
        txtA_ShowResuilt.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtA_ShowResuilt.setRows(5);
        txtA_ShowResuilt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtA_ShowResuilt);

        btn_TT_Dt.setText("Thông Tin");
        btn_TT_Dt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TT_DtActionPerformed(evt);
            }
        });

        btn_Hien_lk.setText("Chi tiết(Hiện liên kết)");
        btn_Hien_lk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Hien_lkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnHien_DT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_TT_Dt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Hien_lk)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHien_DT)
                    .addComponent(btn_TT_Dt)
                    .addComponent(btn_Hien_lk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pNShow2.setBackground(new java.awt.Color(204, 204, 204));
        pNShow2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 51, 204)));
        pNShow2.setPreferredSize(new java.awt.Dimension(861, 401));
        pNShow2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pNShow2MouseMoved(evt);
            }
        });
        pNShow2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pNShow2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pNShow2Layout = new javax.swing.GroupLayout(pNShow2);
        pNShow2.setLayout(pNShow2Layout);
        pNShow2Layout.setHorizontalGroup(
            pNShow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        pNShow2Layout.setVerticalGroup(
            pNShow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 255)));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnChay.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        btnChay.setText("Paint");
        btnChay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        btnChay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChayActionPerformed(evt);
            }
        });

        btnAutoNoi.setText("nối tự động");
        btnAutoNoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAutoNoi.setEnabled(false);
        btnAutoNoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoNoiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBChi_Dinh);
        rBChi_Dinh.setSelected(true);
        rBChi_Dinh.setText("Chỉ vẽ Đỉnh");
        rBChi_Dinh.setContentAreaFilled(false);
        rBChi_Dinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBChi_DinhActionPerformed(evt);
            }
        });

        rBDinh_Canh.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rBDinh_Canh);
        rBDinh_Canh.setText("Vẽ đỉnh và cạnh(cung)");
        rBDinh_Canh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBDinh_CanhActionPerformed(evt);
            }
        });

        btn_repair_vohuong.setText("Vẽ lại");
        btn_repair_vohuong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_repair_vohuong.setEnabled(false);
        btn_repair_vohuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_repair_vohuongActionPerformed(evt);
            }
        });

        rBCanh_max.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rBCanh_max);
        rBCanh_max.setText("Liên kết tất cả các cạnh");
        rBCanh_max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBCanh_maxActionPerformed(evt);
            }
        });

        rBChi_Canh.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rBChi_Canh);
        rBChi_Canh.setText("Chỉ vẽ Cạnh(Cung)");
        rBChi_Canh.setEnabled(false);
        rBChi_Canh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBChi_CanhActionPerformed(evt);
            }
        });

        rB_Khuyen.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rB_Khuyen);
        rB_Khuyen.setText("vẽ Khuyên");
        rB_Khuyen.setEnabled(false);
        rB_Khuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rB_KhuyenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel1.setText(" Đồ Thị Vô Hướng");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(154, 154, 154))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_repair_vohuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAutoNoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rBDinh_Canh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rBChi_Canh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rB_Khuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rBChi_Dinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(rBCanh_max))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnChay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnAutoNoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_repair_vohuong))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rBChi_Dinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBChi_Canh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rB_Khuyen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBDinh_Canh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBCanh_max)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 3));

        btnMaTran_DinhCanh.setText("Ma Trận Đỉnh - Cạnh(Cung)");
        btnMaTran_DinhCanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaTran_DinhCanhActionPerformed(evt);
            }
        });

        btnDanhSachKe.setText("Danh Sách Kề");
        btnDanhSachKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachKeActionPerformed(evt);
            }
        });

        btnDuyetDoTHi.setText("Duyệt Đồ Thị");
        btnDuyetDoTHi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuyetDoTHiActionPerformed(evt);
            }
        });

        jLabel2.setText("Thuật Toán đồ thị vô hướng:");

        buttonGroup2.add(rB_Duyetdothi_BFS);
        rB_Duyetdothi_BFS.setText("BFS");
        rB_Duyetdothi_BFS.setEnabled(false);
        rB_Duyetdothi_BFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rB_Duyetdothi_BFSActionPerformed(evt);
            }
        });

        buttonGroup2.add(rB_DuyetDoThi_DFS);
        rB_DuyetDoThi_DFS.setSelected(true);
        rB_DuyetDoThi_DFS.setText("DFS");
        rB_DuyetDoThi_DFS.setEnabled(false);
        rB_DuyetDoThi_DFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rB_DuyetDoThi_DFSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnDanhSachKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMaTran_DinhCanh, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDuyetDoTHi, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(rB_Duyetdothi_BFS)
                        .addGap(54, 54, 54)
                        .addComponent(rB_DuyetDoThi_DFS)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMaTran_DinhCanh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDanhSachKe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(btnDuyetDoTHi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rB_Duyetdothi_BFS)
                    .addComponent(rB_DuyetDoThi_DFS))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 3));

        txtA_temp.setColumns(20);
        txtA_temp.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtA_temp.setRows(5);
        txtA_temp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtA_temp);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Kết quả:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pNShow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pNShow2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName(" ");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 102, 255)));

        jMenu2.setText("Loại Đồ Thị");
        jMenu2.setToolTipText("");

        jMenuItem2.setText("Đồ thị vô hướng");
        jMenuItem2.setSelected(true);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem1.setText("Đồ thị có hướng");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnChayActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnChayActionPerformed
        xacnhan = !xacnhan;
        if (xacnhan) {
            btnChay.setBackground(new Color(0, 191, 255));
            rBChi_Dinh.setEnabled(true);
            rBDinh_Canh.setEnabled(false);
            rBCanh_max.setEnabled(false);
            btnChay.setText("stop");
        }
        if (xacnhan && rBChi_Dinh.isSelected()) {
            btnChay.setText("stop");
            select = 1;
        } else if (xacnhan && rBDinh_Canh.isSelected()) {
            btnChay.setText("stop");
            select = 2;
        } else if (xacnhan && rBCanh_max.isSelected()) {
            btnChay.setText("stop");
            select = 3;
        } else if (xacnhan && rBChi_Canh.isSelected()) {
            btnChay.setText("stop");
            select = 4;
        } else if (xacnhan && rB_Khuyen.isSelected()) {
            btnChay.setText("stop");
            select = 5;
        } else {
            select = 0;
            xacnhan = false;
            btnChay.setText("Paint");
            this.pO.temp_n = t;
            btnChay.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btnChayActionPerformed
    void Paint_Point(int x, int y, Color c) {
        this.pO.Bong(x, y, c);
        this.pO.fillChar(x, y, t);

    }
    private void pNShow2MouseClicked(MouseEvent evt) {//GEN-FIRST:event_pNShow2MouseClicked

        if (xacnhan && select == 2) {
            this.Chay_ve_Canh_Diem(evt.getX(), evt.getY());
        } else if (xacnhan && select == 1) {
            this.Chay_Ve_Diem(evt.getX(), evt.getY());
        } else if (xacnhan && select == 3) {
            this.Chay_Ve_Max_Canh(evt.getX(), evt.getY());
        } else if (xacnhan && select == 4) {
            this.Chay_Ve_Canh(evt.getX(), evt.getY());
        } else if (xacnhan && select == 5) {
            this.Chay_Ve_Khuyen(evt.getX(), evt.getY());
        }
        if (t == 1) {
            rB_Khuyen.setEnabled(true);
            rBChi_Canh.setEnabled(true);
        }
        if (temp_DuyetDothi == 1) {
            if (duyet_Dothi_DFS) {
                pO.fill_mau_all_dinh(evt.getX(), evt.getY());
                pO.fill_mau_dinh(evt.getX(), evt.getY(), Color.red);
                txtA_temp.setText(pO.DuyetDoThi_DFS(evt.getX(), evt.getY()));
            } else {
                pO.fill_mau_all_dinh(evt.getX(), evt.getY());
                pO.fill_mau_dinh(evt.getX(), evt.getY(), Color.MAGENTA);
                txtA_temp.setText(pO.DuyetDoThi_BFS(evt.getX(), evt.getY()));
            }
        }

    }//GEN-LAST:event_pNShow2MouseClicked

    private void btnAutoNoiActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAutoNoiActionPerformed
        pO.Line(t, this.pO.x, this.pO.y);
    }//GEN-LAST:event_btnAutoNoiActionPerformed

    private void btn_repair_vohuongActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn_repair_vohuongActionPerformed
        this.revalidate();
        this.repaint();
        sL_Resize.setValue(40);
        select = 0;
        t = 0;
        xacnhan = false;
        btnAutoNoi.setEnabled(false);
        rBChi_Dinh.setEnabled(false);
        rBDinh_Canh.setEnabled(false);
        rBCanh_max.setEnabled(false);
        rBChi_Canh.setEnabled(false);
        rB_Khuyen.setEnabled(false);
        btnChay.setBackground(Color.WHITE);
        btn_repair_vohuong.setEnabled(false);
        rBChi_Dinh.setSelected(true);
        txtA_ShowResuilt.setText("");
        pO = new paintOval(pNShow2.getGraphics());
        btnChay.setText("Paint");

        //duyet do thi
        temp_DuyetDothi = 0;
        duyet_Dothi_DFS = false;
        duyet_Dothi_BFS = false;
        btnDuyetDoTHi.setText("Duyệt Đồ Thị");
        btnDuyetDoTHi.setBackground(Color.WHITE);
        rB_DuyetDoThi_DFS.setEnabled(false);
        rB_Duyetdothi_BFS.setEnabled(false);

        //DS ke
        temp_hienDSKe = 0;
        btnDanhSachKe.setText("Danh Sách Kề");
        btnDanhSachKe.setBackground(Color.white);

        //MT dinh canh cung
        temp_hienMatran = 0;
        btnMaTran_DinhCanh.setText("Ma Trận Đỉnh - Cạnh(Cung)");
        btnMaTran_DinhCanh.setBackground(Color.white);


    }//GEN-LAST:event_btn_repair_vohuongActionPerformed

    private void rBChi_DinhActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rBChi_DinhActionPerformed
        if (xacnhan && rBChi_Dinh.isSelected()) {
            select = 1;
        }
    }//GEN-LAST:event_rBChi_DinhActionPerformed

    private void rBDinh_CanhActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rBDinh_CanhActionPerformed
        if (xacnhan && rBDinh_Canh.isSelected()) {
            select = 2;
        }
    }//GEN-LAST:event_rBDinh_CanhActionPerformed

    private void rBCanh_maxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rBCanh_maxActionPerformed
        if (xacnhan && rBCanh_max.isSelected()) {
            select = 3;
        }
    }//GEN-LAST:event_rBCanh_maxActionPerformed

    private void jMenuItem2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void rBChi_CanhActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rBChi_CanhActionPerformed
        if (xacnhan && rBChi_Canh.isSelected()) {
            select = 4;

        }
    }//GEN-LAST:event_rBChi_CanhActionPerformed

    private void rB_KhuyenActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rB_KhuyenActionPerformed
        if (xacnhan && rB_Khuyen.isSelected())
            select = 5;
    }//GEN-LAST:event_rB_KhuyenActionPerformed

    private void pNShow2MouseMoved(MouseEvent evt) {//GEN-FIRST:event_pNShow2MouseMoved

        if (xacnhan) {
            if (t >= 0 && hienTT) {
                Thong_tin_DT();
            } else if (t >= 0 && hienLK) {
                Hien_lk(this.pO.son_lk, this.pO.son_lk);
            } else if (t >= 0 && hienMaTran) {
                hien_MaTran(this.pO.son_lk, this.pO.son_lk);
            }
        }
        if (xacnhan && (select == 1 || select == 2 || select == 3) && (evt.getX() < 850 && evt.getY() < 400) && (evt.getX() > 10 && evt.getY() > 10)) {
            setCursor(HAND_CURSOR);
        } else {
            setCursor(DEFAULT_CURSOR);
        }

    }//GEN-LAST:event_pNShow2MouseMoved

    private void btnHien_DTActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnHien_DTActionPerformed
        hien_MaTran(this.pO.son_lk, this.pO.son_lk);
    }//GEN-LAST:event_btnHien_DTActionPerformed

    private void btn_Hien_lkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Hien_lkActionPerformed
        Hien_lk(this.pO.son_lk, this.pO.son_lk);
    }//GEN-LAST:event_btn_Hien_lkActionPerformed

    private void btn_TT_DtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TT_DtActionPerformed
        Thong_tin_DT();

    }//GEN-LAST:event_btn_TT_DtActionPerformed
    int temp_hienMatran = 0;
    private void btnMaTran_DinhCanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaTran_DinhCanhActionPerformed
        temp_hienMatran++;
        if (temp_hienMatran == 1) {
            Hien_MaTran_DinhCung(t, t, pO.x, pO.y);
            btnMaTran_DinhCanh.setText("Dừng");

        } else if (temp_hienMatran == 2) {
            Hien_MaTran_DinhCung(t, t, pO.x, pO.y);
            temp_hienMatran = 0;
            btnMaTran_DinhCanh.setText("Ma Trận Đỉnh - Cạnh(Cung)");
            btnMaTran_DinhCanh.setBackground(Color.white);
        }
    }//GEN-LAST:event_btnMaTran_DinhCanhActionPerformed

    int temp_hienDSKe = 0;
    private void btnDanhSachKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachKeActionPerformed
        temp_hienDSKe++;
        if (temp_hienDSKe == 1) {

            DanhSachKe();
            btnDanhSachKe.setText("Dừng");
            btnDanhSachKe.setBackground(new Color(0, 191, 255));
//            btnDuyetDoTHi.setBackground(Color.white);
//            btnHien_DT.setBackground(Color.white);
//            btnMaTran_DinhCanh.setBackground(Color.white);  
//            btn_Hien_lk.setBackground(Color.white);
//            btn_TT_Dt.setBackground(Color.white);
        } else if (temp_hienDSKe == 2) {
            temp_hienDSKe = 0;
            btnDanhSachKe.setText("Danh Sách Kề");
            btnDanhSachKe.setBackground(Color.white);
        }


    }//GEN-LAST:event_btnDanhSachKeActionPerformed

    //Đuyet Do Thi
    int temp_DuyetDothi = 0;
    private void btnDuyetDoTHiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuyetDoTHiActionPerformed
        temp_DuyetDothi++;
        if (temp_DuyetDothi == 1) {
//           DuyetDoThi();
            rB_DuyetDoThi_DFS.setEnabled(true);
            rB_Duyetdothi_BFS.setEnabled(true);
            if (rB_DuyetDoThi_DFS.isSelected()) {
                xacnhan = false;
                select = 0;
                btnChay.setText("Paint");
                this.pO.temp_n = t;
                btnChay.setBackground(Color.WHITE);
                duyet_Dothi_DFS = true;
                duyet_Dothi_BFS = false;
                btnDuyetDoTHi.setText("Dừng");
                btnDuyetDoTHi.setBackground(new Color(0, 191, 255));
            } else if (rB_Duyetdothi_BFS.isSelected()) {
                xacnhan = false;
                duyet_Dothi_DFS = false;
                duyet_Dothi_BFS = true;
                select = 0;
                btnChay.setText("Paint");
                this.pO.temp_n = t;
                btnChay.setBackground(Color.WHITE);
                btnDuyetDoTHi.setText("Dừng");
                btnDuyetDoTHi.setBackground(new Color(0, 191, 255));
            }
        } else if (temp_DuyetDothi == 2) {
            temp_DuyetDothi = 0;
            duyet_Dothi_DFS = false;
            duyet_Dothi_BFS = false;
            btnDuyetDoTHi.setText("Duyệt Đồ Thị");
            btnDuyetDoTHi.setBackground(Color.WHITE);
            rB_DuyetDoThi_DFS.setEnabled(false);
            rB_Duyetdothi_BFS.setEnabled(false);
        }
    }//GEN-LAST:event_btnDuyetDoTHiActionPerformed

    private void rB_DuyetDoThi_DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rB_DuyetDoThi_DFSActionPerformed
        duyet_Dothi_DFS = true;
        duyet_Dothi_BFS = false;
    }//GEN-LAST:event_rB_DuyetDoThi_DFSActionPerformed

    private void rB_Duyetdothi_BFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rB_Duyetdothi_BFSActionPerformed
        duyet_Dothi_DFS = false;
        duyet_Dothi_BFS = true;
    }//GEN-LAST:event_rB_Duyetdothi_BFSActionPerformed

    private void sL_ResizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sL_ResizeStateChanged
        Resize_boll_Run();
    }//GEN-LAST:event_sL_ResizeStateChanged

    private void char_Resize1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_char_Resize1StateChanged
        resize_char();
    }//GEN-LAST:event_char_Resize1StateChanged
    //thong tin
    void Thong_tin_DT() {
        String temp_Show_thong_tin = "";
        temp_Show_thong_tin += "- Tổng Đỉnh: " + (t) + "\n- Tổng Bậc: " + this.pO.Tong_bac() + "\n- Tổng Cạnh: " + pO.temp_So_Canh + "\n- Tổng cạnh(có khuyên): " + pO.Tong_bac() / 2 + "\n- Canh Song Song: " + pO.so_canh_SS + "\n- Khuyen: " + (pO.Tong_bac() / 2 - pO.temp_So_Canh);
        temp_Show_thong_tin += "\n- Loại Đồ Thị: " + Loai_DT() + "\n- Dạng Đồ thị: " + Dang_DT();
        txtA_ShowResuilt.setText(temp_Show_thong_tin);
        btnHien_DT.setBackground(Color.white);
        btn_Hien_lk.setBackground(Color.white);
        hienTT = true;
        hienLK = false;
        hienMaTran = false;
        btn_TT_Dt.setBackground(new Color(0, 191, 255));
    }

    //resize char
    void resize_char() {
        lbchar_Show1.setText(char_Resize1.getValue() + "");

        if (char_Resize1.getValue() > 28 || char_Resize1.getValue() < 10) {
            JOptionPane.showMessageDialog(this, "khổ chữ ko hợp lệ");
            char_Resize1.setValue(18);
            resize_char();
        } else {
            Font font = new Font("Monospaced", Font.BOLD, char_Resize1.getValue());
            txtA_temp.setFont(font);
            txtA_ShowResuilt.setFont(font);

        }
        char_Resize1.setValue(char_Resize1.getValue());
    }

    //method resize
    void Resize_boll_Run() {
        lbSl_Show.setText(sL_Resize.getValue() + "");
        this.pO.resize = sL_Resize.getValue();
        if (t > 0) {
            if (temp_resize >= sL_Resize.getValue()) {
                this.pO.del_boll(temp_resize);
            }
            this.pO.Resize_boll();
            temp_resize = sL_Resize.getValue();

            if (sL_Resize.getValue() <= 10) {
                JOptionPane.showMessageDialog(null, "Kích thước quá nhỏ");
                sL_Resize.setValue(40);
            }
        }
    }

    //hien ma tran
    void hien_MaTran(int tempx, int tempy) {
        String temp_show = "Ma Trận Kề: \n";
        for (int i = 0; i <= tempx; i++) {
            for (int j = 0; j <= tempy; j++) {
                temp_show += this.pO.lk_Point[i][j] + " ";
            }
            temp_show += "\n";
        }
        txtA_ShowResuilt.setText(temp_show);
        hienTT = false;
        hienLK = false;
        hienMaTran = true;
        btnHien_DT.setBackground(new Color(0, 191, 255));
        btn_TT_Dt.setBackground(Color.white);
        btn_Hien_lk.setBackground(Color.white);
    }

    //-------------------------MaTran Dinh_cung
    boolean dem_i_HaiChieu(int i, int j, int temp_dem[], int n) {
        for (int k = 0; k <= n;) {
            if (temp_dem[k] == j && temp_dem[(k + 1)] == i) {
                return false;
            }
            k += 2;
        }
        return true;
    }

//    void Reset_tsCanh() {
//        for (int i = 0; i <= t; i++) {
//            pO.fillChar_canh(pO.x[i],pO.y[i] , i, new Color(204, 204, 204));
//        }
//        i++;
//    }
    void Hien_MaTran_DinhCung(int tempx, int tempy, int pointx[], int pointy[]) {
        String temp_show = "Ma Trận đỉnh cung: \n\nCạnh   \t";
        int lk_canh[][] = new int[100][100];
        int x_temp[] = new int[100];
        int y_temp[] = new int[100];
        int temp_lkdc = 0;
        int temp_point = 0;

        int so_canh = pO.temp_So_Canh;
        int temp_dem[] = new int[100];
        int temp_dem_sl = 0;

        //xet
        for (int i = 0; i <= tempx; i++) {
            for (int j = 0; j <= tempy; j++) {
                if (this.pO.lk_Point[i][j] == 1 && dem_i_HaiChieu(i, j, temp_dem, (temp_dem_sl - 2))) {
                    x_temp[temp_point] = (int) ((pointx[i] + pointx[(j)]) / 2);
                    y_temp[temp_point] = (int) ((pointy[i] + pointy[(j)]) / 2);
                    pO.fillChar_canh(x_temp[temp_point] + 20, y_temp[temp_point] - 20, temp_lkdc, new Color(204, 204, 204));
                    if (temp_hienMatran == 1) {
                        pO.fillChar_canh(x_temp[temp_point] + 20, y_temp[temp_point] - 20, temp_lkdc, Color.blue);
                    }
                    temp_dem[temp_dem_sl] = i;
                    lk_canh[i][temp_lkdc] = 1;
                    lk_canh[j][temp_lkdc] = 1;
                    temp_lkdc++;
                    temp_dem[(temp_dem_sl + 1)] = j;
                    temp_dem_sl += 2;
                    temp_point++;
                }
            }
        }
        for (int k = 0; k < temp_lkdc; k++) {
            temp_show += "e" + (k + 1) + "   ";
        }
        for (int i = 0; i < tempy; i++) {
            temp_show += "\nĐỉnh " + (i + 1) + "\t";
            for (int j = 0; j < so_canh; j++) {
                temp_show += lk_canh[i][j] + "     ";

            }

        }
//        Hien_canh(temp_dem, temp_lkdc, pointx, pointy);
        txtA_temp.setText(temp_show);
        btnMaTran_DinhCanh.setBackground(new Color(0, 191, 255));
    }

//    void Hien_canh(int temp_dem[], int temp_lkdc, int pointx[], int pointy[]) {
//        int x_temp = 0;
//        int y_temp = 0;
//        for (int j = 0; j <= temp_lkdc;) {
//
//            x_temp = (int) ((pointx[j] + pointx[(j + 1)])) / 2;
//            y_temp = (int) ((pointy[j] + pointy[(j + 1)])) / 2;
//
//            pO.fillChar_canh(x_temp, y_temp, j, new Color(204, 204, 204));
//            j++;
//        }
//    }
    //hien lien ket
    void Hien_lk(int tempx, int tempy) {
        String lk = "";
        for (int i = 0; i <= tempx; i++) {
            for (int j = 0; j <= tempy; j++) {
                int temp = this.pO.lk_Point[i][j];
                if (temp > 0) {
                    lk += "D(" + (i + 1) + ")" + " - " + "D(" + (j + 1) + ")" + "\t";
                }
            }
            lk += "=> deg(" + (i + 1) + ") = " + pO.So_Bac[i] + "\n\n";
        }
        txtA_ShowResuilt.setText(lk);
        hienTT = false;
        hienLK = true;
        hienMaTran = false;
        btn_Hien_lk.setBackground(new Color(0, 191, 255));
        btnHien_DT.setBackground(Color.white);
        btn_TT_Dt.setBackground(Color.white);
    }

    //xet loai do thi
    String Loai_DT() {
        String loai = "Đơn đồ thị vô hướng";
        if (this.pO.song_Song && this.pO.Khuyen_co) {
            loai = "Giả đồ thị vô hướng";
        } else if (this.pO.song_Song) {
            loai = "Đa đồ thị vô hướng";
        }
        return loai;
    }

    boolean Kiemtra_LuongPhan() {
        int x_dat = 0;
        int temp_y = 0;
        int temp_t = 0;
        int x_dem[] = new int[100];
        int y_dem[] = new int[100];
        int t_dem[] = new int[100];
        for (int i = 0; i <= t; i++) {
            if (pO.lk_Point[0][i] == 1) {
                y_dem[temp_y] = i;
                temp_y++;
            }
        }
        for (int i = 0; i < temp_y; i++) {
            for (int j = 0; j <= t; j++) {
                if (pO.lk_Point[y_dem[i]][j] == 1) {
                    if (dem_i(i, t_dem, temp_t)) {
                        t_dem[temp_t] = j;
                        temp_t++;
                    }
                }
            }
        }
        for (int i = 0; i < temp_y; i++) {
            for (int j = 0; j < temp_t; j++) {
                if (y_dem[i] == t_dem[j]) {
                    return false;
                }

            }
        }
        return kiemtra_LuongPhanTT(2, x_dem, y_dem, t_dem, temp_y, temp_t);
    }

    boolean dem_i(int i, int t_dem[], int temp_t) {
        for (int k = 0; k < temp_t; k++) {
            if (t_dem[k] == i) {
                return false;
            }

        }
        return true;
    }

    boolean kiemtra_LuongPhanTT(int n, int x_dem[], int y_dem[], int t_dem[], int temp_y, int temp_t) {
        int temp_x = 0;
        x_dem[temp_x] = 0;
        boolean tt = false;
        int temp_yy = 0;
        int temp_tt = 0;
        for (int h = 0; h < n; h++) {
            if (tt) {
                temp_t = temp_yy;
            }
            tt = true;
            for (int i = 0; i < temp_t; i++) {
                temp_x++;
                if (dem_i(i, x_dem, temp_x - 1)) {
                    x_dem[temp_x] = t_dem[i];
                }
            }
            for (int i = 0; i <= temp_x; i++) {
                for (int j = 0; j < t; j++) {
                    if (pO.lk_Point[x_dem[i]][j] == 1) {
                        if (dem_i(i, y_dem, temp_yy)) {
                            y_dem[temp_yy] = j;
                            temp_yy++;
                        }

                    }
                }
            }
            for (int i = 0; i < temp_yy; i++) {
                for (int j = 0; j <= t; j++) {
                    if (pO.lk_Point[y_dem[i]][j] == 1) {
                        if (dem_i(i, t_dem, temp_tt)) {
                            t_dem[temp_tt] = j;
                            temp_tt++;
                        }

                    }
                }
            }
            for (int i = 0; i < temp_tt; i++) {
                for (int j = 0; j < temp_yy; j++) {
                    if (y_dem[j] == t_dem[i]) {
                        return false;
                    }
                }
            }
        }
        return true;
    }

    boolean DoThi_banh_Xe(boolean temp2) {
        int temp_dinh_3 = 0;
        boolean temp_dinh_n = false;
        for (int i = 0; i <= t; i++) {
            if (pO.So_Bac[i] == 3) {
                temp_dinh_3++;
            } else if (pO.So_Bac[i] == t - 1) {
                temp_dinh_n = true;
            }
        }
        if (temp_dinh_3 == t - 1 && temp_dinh_n) {
            return true;
        }
        if (t == 4 && temp2) {
            return true;
        }
        return false;
    }

    String Dang_DT() {
        String dang = "";
        String dang_DoT[] = {"Đồ thị đầy đủ", "Đồ thị vòng", "Đồ thị Bánh xe", "Đồ thị lưỡng phân", "Đồ thị lưỡng phân đủ", "Đồ thị hình sao"};
        boolean co_Dang[] = new boolean[6];
        int temp = 0;
        for (int i = 0; i <= 5; i++) {
            co_Dang[i] = false;
        }
        if (t < 3 || this.pO.temp_So_Canh < 3) {
            return "I don't know";
        } else {
            for (int i = 0; i <= t; i++) {
                if (pO.So_Bac[i] == (t - 1) && this.pO.temp_So_Canh == (t * (t - 1)) / 2) {
                    co_Dang[0] = true;
                }
                if (pO.So_Bac[i] == 2 && this.pO.temp_So_Canh == t) {
                    co_Dang[1] = true;
                }

            }
            if (DoThi_banh_Xe(co_Dang[0])) {
                co_Dang[2] = true;

            }
            if (Kiemtra_LuongPhan()) {
                co_Dang[3] = true;
            }
            for (int i = 0; i <= 5; i++) {
                if (co_Dang[i]) {
                    dang += " " + dang_DoT[i];
                    temp++;
                }
            }
            if (temp < 1) {
                dang = "I don't know";
            }

        }
        temp = 0;
        co_Dang = new boolean[5];

        return dang;
    }

    // chi ve diem
    void Chay_Ve_Diem(int x, int y) {
        this.pO.x[t] = x;
        this.pO.y[t] = y;
        this.pO.temp_FillChar = t;
        Paint_Point(x, y, Color.BLACK);
        thread_2 = new Thread(pO);
        thread_2.start();
        t++;
        System.out.println(t);
        if (t >= 0) {
            btnAutoNoi.setEnabled(false);
            btn_repair_vohuong.setEnabled(true);
            sL_Resize.setEnabled(true);
        }
    }

    // chi ve canh
    void Chay_Ve_Canh(int x, int y) {
        if (t != 0) {
            this.pO.Ve_Canh(t, x, y, this.pO.x, this.pO.y);
            thread_2 = new Thread(pO);
            thread_2.start();
        }
    }
    // Ve Khuyen

    void Chay_Ve_Khuyen(int x, int y) {
        if (t != 0) {
            this.pO.ve_Khuyen(t, x, y, this.pO.x, this.pO.y);
            thread_2 = new Thread(pO);
            thread_2.start();
            btnAutoNoi.setEnabled(false);
            btn_repair_vohuong.setEnabled(true);
        }
    }

    // Chay ve canh va diem
    void Chay_ve_Canh_Diem(int x, int y) {
        this.pO.x[t] = x;
        this.pO.y[t] = y;
        this.pO.temp_FillChar = t;
        Paint_Point(x, y, Color.BLACK);
        this.pO.AutoLine(t, pO.x, pO.y);
        thread_2 = new Thread(pO);
        thread_2.start();
        t++;
        System.out.println(t);
        if (t >= 0) {
            btnAutoNoi.setEnabled(false);
            btn_repair_vohuong.setEnabled(true);
        }
    }

    //Ve voi so canh lon nhat
    void Chay_Ve_Max_Canh(int x, int y) {
        this.pO.x[t] = x;
        this.pO.y[t] = y;
        this.pO.temp_FillChar = t;
        Paint_Point(x, y, Color.BLACK);
        this.pO.AutoLine_vohuong_full(t, pO.x, pO.y);
        thread_2 = new Thread(pO);
        thread_2.start();
        t++;
        System.out.println(t);
        if (t >= 0) {
            btnAutoNoi.setEnabled(false);
            btn_repair_vohuong.setEnabled(true);
        }
    }

    void DanhSachKe() {
        int i_dem[] = new int[100];
        int temp_i = 0;
        int tro[] = new int[100];
        String chuoiString = "Danh Sách Kề: \n\tDS 1:";
        int temp_dSK = 0;
        tro[0] = temp_dSK;
        for (int i = 0; i <= t; i++) {
            for (int j = 0; j <= t; j++) {
                if (pO.lk_Point[i][j] == 1) {
                    i_dem[temp_i] = j;
                    temp_i++;

                }
            }
            temp_dSK++;
            tro[temp_dSK] = temp_i;
        }
        int demp_ds = 1;

        for (int i = 0; i <= temp_i; i++) {
            chuoiString += " " + (i_dem[i] + 1) + " ->";
            if ((tro[demp_ds] - 1) == i) {
                demp_ds++;
                chuoiString += "NULL";
                if (demp_ds < temp_dSK) {
                    chuoiString += "\n\tDS " + demp_ds + ":";
                }
            }
            txtA_temp.setText(chuoiString);
            if (demp_ds >= temp_dSK) {
                break;
            }
        }
    }

    //Duyet do thi
    void DuyetDoThi() {
        String a = "";
        for (int i = 0; i <= t; i++) {
            for (int j = 0; j <= t; j++) {
                a += pO.lk_Point[i][j] + "";
            }
        }
        pO.Luu_Dt();
        txtA_ShowResuilt.setText(a);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(From_DoAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(From_DoAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(From_DoAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(From_DoAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new From_DoAn().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoNoi;
    private javax.swing.JButton btnChay;
    private javax.swing.JButton btnDanhSachKe;
    private javax.swing.JButton btnDuyetDoTHi;
    private javax.swing.JButton btnHien_DT;
    private javax.swing.JButton btnMaTran_DinhCanh;
    private javax.swing.JButton btn_Hien_lk;
    private javax.swing.JButton btn_TT_Dt;
    private javax.swing.JButton btn_repair_vohuong;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JSlider char_Resize1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbSl_Show;
    private javax.swing.JLabel lbchar_Show1;
    private javax.swing.JPanel pNShow2;
    private javax.swing.JRadioButton rBCanh_max;
    private javax.swing.JRadioButton rBChi_Canh;
    private javax.swing.JRadioButton rBChi_Dinh;
    private javax.swing.JRadioButton rBDinh_Canh;
    private javax.swing.JRadioButton rB_DuyetDoThi_DFS;
    private javax.swing.JRadioButton rB_Duyetdothi_BFS;
    private javax.swing.JRadioButton rB_Khuyen;
    private javax.swing.JSlider sL_Resize;
    private javax.swing.JTextArea txtA_ShowResuilt;
    private javax.swing.JTextArea txtA_temp;
    // End of variables declaration//GEN-END:variables
}
